# Generated by Django 5.2.6 on 2025-10-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skill_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
