# Generated by Django 5.2.6 on 2025-10-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_application_skill_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='skill_list',
            field=models.TextField(verbose_name='Ваши навыки'),
        ),
    ]
