# Generated by Django 5.2.6 on 2026-03-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_application_requirement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skills_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Навыки (структурированные)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='skill_list',
            field=models.TextField(blank=True, default='JS, REACT, TypeScript', verbose_name='Ваши навыки'),
        ),
    ]
