# Generated by Django 5.2.6 on 2026-03-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_application_skills_json_alter_application_skill_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='solution_description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='solution_experience',
        ),
        migrations.RemoveField(
            model_name='application',
            name='solution_name',
        ),
        migrations.AddField(
            model_name='application',
            name='about_me',
            field=models.TextField(blank=True, default='', verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='application',
            name='team_role',
            field=models.CharField(blank=True, choices=[('developer', 'Разработчик'), ('frontend', 'Frontend-разработчик'), ('backend', 'Backend-разработчик'), ('fullstack', 'Fullstack-разработчик'), ('mobile', 'Мобильный разработчик'), ('devops', 'DevOps-инженер'), ('designer', 'Дизайнер'), ('ui_ux', 'UI/UX-дизайнер'), ('project_manager', 'Проектный менеджер'), ('product_manager', 'Продуктовый менеджер'), ('team_lead', 'Тимлид'), ('tech_lead', 'Технический лид'), ('analyst', 'Аналитик'), ('qa', 'QA-инженер'), ('tester', 'Тестировщик'), ('marketing', 'Маркетолог'), ('sales', 'Менеджер по продажам'), ('support', 'Саппорт'), ('other', 'Другое')], default='developer', max_length=50, verbose_name='Роль в команде'),
        ),
    ]
