# Generated by Django 5.2.6 on 2026-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_application_solution_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='application',
            name='age',
        ),
        migrations.RemoveField(
            model_name='application',
            name='requirement_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='requirement_price',
        ),
        migrations.AddField(
            model_name='application',
            name='activity_area',
            field=models.CharField(blank=True, choices=[('it', 'Информационные технологии'), ('energy', 'Энергетика'), ('automation', 'Автоматика'), ('math', 'Математика'), ('economics', 'Экономика'), ('management', 'Менеджмент'), ('business_analysis', 'Бизнес-анализ'), ('other', 'Другое')], default='it', max_length=50, verbose_name='Область деятельности'),
        ),
        migrations.AddField(
            model_name='application',
            name='activity_area_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Другая область деятельности'),
        ),
        migrations.AddField(
            model_name='application',
            name='collaboration_expectations',
            field=models.TextField(blank=True, default='', help_text='Что вы ожидаете от сотрудничества?', verbose_name='Ожидание от сотрудничества'),
        ),
        migrations.AddField(
            model_name='application',
            name='driver_license',
            field=models.BooleanField(default=False, verbose_name='Наличие водительских прав'),
        ),
        migrations.AddField(
            model_name='application',
            name='elibrary_link',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на Elibrary'),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ожидаемое вознаграждение (₽)'),
        ),
        migrations.AddField(
            model_name='application',
            name='github_link',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на GitHub'),
        ),
        migrations.AddField(
            model_name='application',
            name='it_skill',
            field=models.CharField(blank=True, choices=[('information_systems', 'Информационные системы'), ('design', 'Проектирование'), ('ui_development', 'Разработка пользовательского интерфейса'), ('server_development', 'Разработка серверной части'), ('client_development', 'Клиентская часть'), ('other', 'Другое')], default='information_systems', max_length=50, verbose_name='Ключевые навыки в IT'),
        ),
        migrations.AddField(
            model_name='application',
            name='it_skill_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Другие ключевые навыки'),
        ),
        migrations.AddField(
            model_name='application',
            name='leaderid_link',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на LeaderID'),
        ),
        migrations.AddField(
            model_name='application',
            name='project_examples',
            field=models.TextField(blank=True, default='', help_text='Опишите ваши проекты, можно добавить ссылки', verbose_name='Примеры проектов'),
        ),
        migrations.AddField(
            model_name='application',
            name='required_equipment',
            field=models.TextField(blank=True, default='', help_text='Какое оборудование необходимо для работы', verbose_name='Требуемое оборудование'),
        ),
        migrations.AddField(
            model_name='application',
            name='team_role_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Другая роль'),
        ),
        migrations.AddField(
            model_name='application',
            name='technology',
            field=models.CharField(blank=True, choices=[('programming_language', 'Язык программирования'), ('database', 'СУБД'), ('framework', 'Фреймворк'), ('library', 'Библиотека'), ('other', 'Другое')], default='programming_language', max_length=50, verbose_name='Знание технологий'),
        ),
        migrations.AddField(
            model_name='application',
            name='technology_details',
            field=models.TextField(blank=True, default='', help_text='Перечислите конкретные технологии, языки, СУБД, фреймворки и т.д.', verbose_name='Детальное описание технологий'),
        ),
        migrations.AddField(
            model_name='application',
            name='technology_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Другие технологии'),
        ),
        migrations.AddField(
            model_name='application',
            name='work_experience',
            field=models.TextField(blank=True, default='', help_text='Опишите ваш опыт работы', verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='application',
            name='work_schedule',
            field=models.CharField(blank=True, choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('flexible', 'Гибкий график'), ('remote', 'Удаленная работа'), ('project_work', 'Проектная работа'), ('other', 'Другое')], default='full_time', max_length=20, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='application',
            name='work_schedule_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Другой график'),
        ),
    ]
