# Generated by Django 5.2.6 on 2026-03-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_application_about_me_remove_application_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='technologies_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Технологии (структурированные)'),
        ),
        migrations.AddField(
            model_name='application',
            name='technologies_text',
            field=models.TextField(blank=True, default='', verbose_name='Технологии (текст)'),
        ),
    ]
