# Generated by Django 5.2.6 on 2026-03-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_application_technologies_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='organization_inn',
        ),
        migrations.RemoveField(
            model_name='application',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='organization_website',
        ),
        migrations.AddField(
            model_name='application',
            name='belbin_role',
            field=models.CharField(blank=True, choices=[('implementer', 'Исполнитель'), ('coordinator', 'Координатор'), ('shaper', 'Формирователь'), ('plant', 'Генератор идей'), ('resource_investigator', 'Разведчик'), ('teamworker', 'Душа команды'), ('monitor_evaluator', 'Аналитик'), ('completer_finisher', 'Педантичность'), ('specialist', 'Специалист')], default='', max_length=30, verbose_name='Роль в команде (по Белбину)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='team_role',
            field=models.CharField(blank=True, choices=[('developer', 'Разработчик'), ('frontend', 'Frontend-разработчик'), ('backend', 'Backend-разработчик'), ('fullstack', 'Fullstack-разработчик'), ('mobile', 'Мобильный разработчик'), ('devops', 'DevOps-инженер'), ('designer', 'Дизайнер'), ('ui_ux', 'UI/UX-дизайнер'), ('project_manager', 'Проектный менеджер'), ('product_manager', 'Продуктовый менеджер'), ('team_lead', 'Тимлид'), ('tech_lead', 'Технический лид'), ('analyst', 'Аналитик'), ('qa', 'QA-инженер'), ('tester', 'Тестировщик'), ('marketing', 'Маркетолог'), ('sales', 'Менеджер по продажам'), ('support', 'Саппорт'), ('other', 'Другое')], default='developer', max_length=50, verbose_name='Ваша специальность'),
        ),
    ]
