# Generated by Django 5.2.6 on 2026-05-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_projectrequirement_level_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/%Y/%m/', verbose_name='Фото профиля'),
        ),
    ]
