# Generated by Django 5.2.6 on 2026-05-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Письмо отправлено'),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки письма'),
        ),
    ]
