# Generated by Django 5.2.6 on 2026-05-23 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_joinrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'verbose_name': 'Запрос на присоединение', 'verbose_name_plural': 'Запросы на присоединение'},
        ),
        migrations.AddField(
            model_name='project',
            name='activity_category',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('energy', 'Энергетика'), ('automation', 'Автоматика'), ('construction', 'Строительство')], max_length=50, verbose_name='Категория деятельности'),
        ),
        migrations.AddField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True, verbose_name='Результаты проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.TextField(blank=True, verbose_name='Технологический стек'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='main.application'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='main.project'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
