# Generated by Django 5.2.6 on 2026-05-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_joinrequest_options_project_activity_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'invitation', 'type')},
        ),
    ]
