# Generated by Django 5.2.6 on 2026-05-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_notification_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
    ]
