# Generated by Django 5.2.6 on 2026-05-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_notification_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'invitation', 'type')},
        ),
    ]
