# Generated by Django 5.2.6 on 2026-03-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.CharField(blank=True, help_text='Введите ключевые слова через запятую', max_length=500, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='belbin_role',
            field=models.CharField(blank=True, choices=[('implementer', 'Исполнитель'), ('coordinator', 'Координатор'), ('shaper', 'Формирователь'), ('plant', 'Генератор идей'), ('resource_investigator', 'Разведчик'), ('teamworker', 'Душа команды'), ('monitor_evaluator', 'Аналитик'), ('completer_finisher', 'Педантичность'), ('specialist', 'Специалист')], help_text='Необязательное поле. Выберите роль, которая требуется для данного навыка', max_length=30, verbose_name='Требуемая роль по Белбину'),
        ),
    ]
